-- Table to store server information
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='SERVERS' AND xtype='U')
BEGIN
    CREATE TABLE SERVERS (
        SERVER_ID INT PRIMARY KEY IDENTITY(1,1),
        SERVER_NAME NVARCHAR(100) NOT NULL,
        SERVER_IP NVARCHAR(50) NOT NULL,
        DESCRIPTION NVARCHAR(255),
        ACTIVE BIT DEFAULT 1,
        CREATED_DATE DATETIME DEFAULT GETDATE(),
        MODIFIED_DATE DATETIME DEFAULT GETDATE()
    );
END
GO

-- Stored procedure to get all active servers
IF EXISTS (SELECT * FROM sysobjects WHERE name='GET_SERVERS' AND xtype='P')
    DROP PROCEDURE GET_SERVERS
GO

CREATE PROCEDURE GET_SERVERS
AS
BEGIN
    SELECT 
        SERVER_ID,
        SERVER_NAME,
        SERVER_IP,
        DESCRIPTION,
        ACTIVE
    FROM SERVERS
    WHERE ACTIVE = 1
    ORDER BY SERVER_NAME
END
GO

-- Insert sample servers (update these IPs as needed)
IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.20')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('Database Server', '10.21.10.20', 'Main SQL Server Database');
END

IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.21')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('Web Server', '10.21.10.21', 'Primary Web Application Server');
END

IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.22')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('API Server', '10.21.10.22', 'REST API Server');
END

IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.23')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('Backup Server', '10.21.10.23', 'Backup and Recovery Server');
END

IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.24')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('File Server', '10.21.10.24', 'Network File Storage');
END

IF NOT EXISTS (SELECT * FROM SERVERS WHERE SERVER_IP = '10.21.10.25')
BEGIN
    INSERT INTO SERVERS (SERVER_NAME, SERVER_IP, DESCRIPTION) 
    VALUES ('App Server 1', '10.21.10.25', 'Application Server Instance 1');
END
GO
